spring:
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

  cache:
    type: redis
    redis:
      time-to-live:
      cache-null-values: false
      enable-statistics: true
      use-key-prefix: true
      key-prefix: cache
logging:
  level:
    root: info
    org.cache: debug
server:
  port: 9001
